portainer:
  container_name: portainer
  image: portainer/portainer
  restart: unless-stopped
  ports:
    - "9002:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volumes/portainer/data:/data
  networks:
    - iotstack_nw
