homer:
  image: b4bz/homer:latest
  container_name: homer
  environment:
    - UID=1000
    - GID=1000
  volumes:
    - ./volumes/homer/assets:/www/assets
  ports:
    - "8881:8080"
  restart: unless-stopped
