postgres:
  container_name: postgres
  image: postgres
  restart: unless-stopped
  environment:
    - POSTGRES_USER=postuser
    - POSTGRES_PASSWORD=%randomPassword%
    - POSTGRES_DB=postdb
  ports:
    - "5432:5432"
  volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
  networks:
    - iotstack_nw
