nextcloud:
  image: nextcloud
  container_name: nextcloud
  ports:
    - "9321:80"
  volumes:
    - ./volumes/nextcloud/html:/var/www/html:rw
  restart: unless-stopped
  depends_on: 
    - nextcloud_db
  links:
    - nextcloud_db
  networks:
    - iotstack_nw
    - nextcloud_internal
  environment:
    - MYSQL_HOST=nextcloud_db
    - MYSQL_PASSWORD=%randomMySqlPassword%
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

nextcloud_db:
  image: linuxserver/mariadb
  container_name: nextcloud_db
  volumes:
    - ./volumes/nextcloud/db:/config
  environment:
    - MYSQL_ROOT_PASSWORD=%randomPassword%
    - MYSQL_PASSWORD=%randomMySqlPassword%
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
  restart: unless-stopped
  networks:
    - nextcloud_internal

